import logging
male = 0
female = 1

ALL_GENDER = [
    (male, "Male"),
    (female, "Female"),
]

BASE_HOST = 'http://localhost:8000/'

REQUESTS_TIMEOUT = 5

LOGGING_LEVEL = logging.WARNING
LOGGING_FORMAT = '%(asctime)s %(levelname)s: %(message)s'

SMS_SERVICE_API_KEY = ''

DIALOGFLOW_PROJECT_ID=''

COUNTRY_ALL = {
    ("united-states", "United States"),
    ("united-kingdom", "United Kingdom"),
    ("france", "France"),
    ("germany", "Germany"),
    ("china", "China"),
    ("india", "India"),
    ("argentina", "Argentina"),
    ("armenia", "Armenia"),
    ("australia", "Australia"),
    ("austria", "Austria"),
    ("bangladesh", "Bangladesh"),
    ("belgium-french", "Belgium (French)"),
    ("belgium-dutch", "Belgium (Dutch)"),
    ("brazil", "Brazil"),
    ("bulgaria", "Bulgaria"),
    ("canada-french", "Canada (French)"),
    ("canada-english", "Canada (English)"),
    ("china", "China"),
    ("croatia", "Croatia"),
    ("cyprus", "Cyprus"),
    ("czech-republic", "Czech Republic"),
    ("denmark", "Denmark"),
    ("finland", "Finland"),
    ("france", "France"),
    ("georgia", "Georgia"),
    ("germany", "Germany"),
    ("greece", "Greece"),
    ("hong-kong", "Hong Kong (English)"),
    ("hungary", "Hungary"),
    ("iceland", "Iceland"),
    ("india", "India"),
    ("indonesia", "Indonesia"),
    ("iran", "Iran"),
    ("israel", "Israel"),
    ("italy", "Italy"),
    ("japan", "Japan"),
    ("jordan", "Jordan"),
    ("kazakhstan", "Kazakhstan"),
    ("latvia", "Latvia"),
    ("lithuania", "Lithuania"),
    ("malaysia", "Malaysia"),
    ("moldova", "Moldova"),
    ("mongolia", "Mongolia"),
    ("nepal", "Nepal"),
    ("netherlands", "Netherlands"),
    ("new-zealand", "New Zealand"),
    ("nigeria", "Nigeria"),
    ("norway", "Norway"),
    ("peru", "Peru"),
    ("philippines", "Philippines"),
    ("poland", "Poland"),
    ("portugal", "Portugal"),
    ("romania", "Romania"),
    ("russia", "Russia"),
    ("saudi-arabia", "Saudi Arabia"),
    ("serbia", "Serbia"),
    ("singapore", "Singapore"),
    ("slovakia", "Slovakia"),
    ("slovenia", "Slovenia"),
    ("south-africa", "South Africa"),
    ("south-korea", "South Korea"),
    ("spain", "Spain"),
    ("sweden", "Sweden"),
    ("switzerland-italian", "Switzerland (Italian)"),
    ("switzerland-german", "Switzerland (German)"),
    ("switzerland-french", "Switzerland (French)"),
    ("taiwan", "Taiwan"),
    ("thailand", "Thailand"),
    ("uganda", "Uganda"),
    ("ukraine", "Ukraine"),
    ("united-kingdom", "United Kingdom"),
    ("united-states", "United States"),
    ("venezuela-spanish", "Venezuela (Spanish)"),
    ("venezuela-english", "Venezuela (English)"),
    ("vietnam", "Vietnam"),
}

PHONE_COUNTRY = [
    (7, "Russia"),
    (86, "China"),
    (86, "China"),
    (7, "Russia"),
    (49, "Germany"),
    (31, "Netherlands"),
    (44, "United Kingdom"),
    (33, "France"),
    (380, "Ukraine"),
    (375, "Belarus"),
    (996, "Kyrgyzstan"),
    (77, "Kazakhstan"),
    (63, "Philippines"),
    (381, "Serbia"),
    (373, "Moldova"),
    (48, "Poland"),
    (43, "Austria"),
    (370, "Lithuania"),
    (371, "Latvia"),
    (372, "Estonia"),
    (998, "Uzbekistan"),
    (20, "Egypt"),
    (234, "Nigeria"),
    (509, "Haiti"),
    (220, "Gambia"),
    (225, "Côte d’Ivoire"),
    (967, "Yemen"),
    (237, "Cameroon"),
    (235, "Chad"),
]
